# numpy demo

## `ndarray` or just array is the main data type we'll be using

* much like java, ndarray is typed
* all elements must be of the same type
   * int64
   * float64
   * obj (native Python)
   * strings....

## creating an `ndarray`

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3, 4])

In [3]:
arr1

array([1, 2, 3, 4])

In [4]:
arr1.dtype

dtype('int32')

In [5]:
arr2d = np.array([[1, 2, 3], [1, 2, 3]])

In [6]:
arr2d

array([[1, 2, 3],
       [1, 2, 3]])

In [8]:
nums = np.arange(1, 10)

In [9]:
nums

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.random.randn(2, 6)

array([[ 1.26499683, -1.58811069, -0.88147966, -0.23825544, -0.76146422,
        -0.80699015],
       [-1.05196869,  0.24007282,  1.48178944, -0.97147291, -0.54583199,
         0.85709517]])

In [8]:
np.random.randn

<function RandomState.randn>

In [14]:
a1 = np.array([[1, 1, 1], [2, 2, 2]])

In [15]:
a1

array([[1, 1, 1],
       [2, 2, 2]])

In [16]:
a1 + 8

array([[ 9,  9,  9],
       [10, 10, 10]])

In [17]:
a1

array([[1, 1, 1],
       [2, 2, 2]])

In [18]:
a1 == 1

array([[ True,  True,  True],
       [False, False, False]])

In [19]:
a1

array([[1, 1, 1],
       [2, 2, 2]])

In [20]:
a1 + np.array([[1, 2, 3], [4, 5, 6]])

array([[2, 3, 4],
       [6, 7, 8]])

In [21]:
a1[0]

array([1, 1, 1])

In [22]:
a1[0][0]

1

In [23]:
big_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

In [24]:
big_arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [25]:
big_arr[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
big_arr[:2, :2]

array([[1, 2],
       [4, 5]])